feat: add card component
Letto228/Angular-learnjs-121222 pull request #100
Opened 2023-01-20 15:20 UTC by AlexandraLushkina

2023-01-22 21:09 UTC, Letto228 requested changes
Привет! Все супер, подметил одну не большую недоработку, посмотри, пожалуйста

2023-01-22 21:09 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +		<button mat-button>Buy</button>
В условии ДЗ был поинт, что нужно отлавливать клик по кнопке и останавливать событие всплытия
Вот, нашел пункт в тексте ДЗ)
> 3. Должна быть кнопка покупки товара. При чем клик по кнопке не должен всплывать до обработчика на самой карточке(`<app-card (click)="...">`).

2023-01-24 16:54 UTC, AlexandraLushkina commented on src/app/products-list/product-card/product-card.component.html
> +		<button mat-button>Buy</button>
Поправила. Посмотри пожалуйста

2023-01-26 04:38 UTC, Letto228 approved these changes
Огонь теперь все по ДЗ - апрув

2023-01-26 04:39 UTC, closed without merging