feat: add popup-host component
Letto228/Angular-learnjs-121222 pull request #102
Opened 2023-01-22 17:32 UTC by IvanBiushkin

Привет
Я правильно понял, что элемент ng-template сам по себе является объектом TemplateRef?

2023-01-23 06:55 UTC, Letto228 requested changes
Привет!
Отлично 👍, по логике вставки шаблона вопросов нет, оставил не большой комментарий по чистоте кода, посмотри, пожалуйста
Есть еще комментарий по отображению `popup-host`, подразумевается, что popup будет отображаться поверх всего контента на странице и перекрывать его, возможно, даже, с общим блюром. Давай добавим стилей, чтобы компонент `popup-host` был поверх всего контента на странице и занимал все окно по площади, я бы посмотрел в сторону `position: fixed`.
Сразу после реализации такого решения возникает вопрос: как скрывать `popup-host`, когда нам не нужно отображать popup на странице, ведь если этого не делать, он перекрывает весь контент и работать с приложением становится не возможно. - В таком случае нужно скрывать `popup-host`, при отсутствии вставленного popup в нем `this.viewContainer.length !== 0 `. Попробуй для скрытия посмотреть в сторону `@HostBinding('style.display') private hostDisplay`. При наличии вставленных элементов в контенер(`this.viewContainer.length !== 0 `) должен применяться стиль `this.hostDisplay = 'block'`, в иных ситуациях(в тех, когда кол-во элементов в контейнере равно нулю) должен применяться стиль `this.hostDisplay = 'none'`.
P.S. можно посмотреть в сторону использования гетера для `@HostBinding('style.display')`

P.S.S. @HostBinding мы рассматривали на 5 лекции в блоке атрибутивных директив.

2023-01-23 06:55 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.ts
> +		if (template && this.popupContainer) {
Сверху ты использовал optional chaining, а тут проверил наличие контейнера через if блок. Предлагаю, чтобы код был чище, использовать один подход:
- Либо везде добавить optional chaining и не делать в if блоке проверку `&& this.popupContainer`
- Либо в самом начале проверить наличие `this.popupContainer` и при его отсутствии воспользоваться ранним ретерном:
```ts
@Input() set popupTemplate(template: TemplateRef<unknown>) {
    if (!this.popupContainer) {
        return;
    }

    this.popupContainer.clear();

    if (template) {
        this.popupContainer.createEmbeddedView(template);
    }
```

2023-01-23 07:05 UTC, Letto228 commented
>Я правильно понял, что элемент ng-template сам по себе является объектом TemplateRef?

Тут такая ситуация: если мы посмотрим на исходники, то поймем, что `ng-tempalte` это просто `HTMLElement`, но Angular обрабатывает этот элемент и подтягивает к нему специальный класс `TemplateRef`, который идеологически является ссылкой на шаблон(элемент `ng-tempalte`).
По этому, если сказать что `ng-template` является объектом `TemplateRef`, то это будет не совсем корректно(но в целом по смыслу верно, если не придираться🙃), корректней будет сказать: `TemplateRef` - ссылка на `ng-tempalte`(шаблон)

Надеюсь, получилось ответить на твой вопрос, если не очень, то можем попробовать подойти с другой стороны, ты только скажи)

2023-01-23 19:04 UTC, IvanBiushkin commented
С ng-tempalte теперь понятно, спасибо)

2023-01-26 04:47 UTC, Letto228 approved these changes
Супер, теперь компонент должен работать корректно
Оставил один комментарий к контейнерам и стилям, посмотри, пожалуйста.

Т.к. коментарий не критичен, оставим его на заметку. Даю апрув и закрываю МР

2023-01-26 04:47 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.html
> +<div class="popup-container">
Кажется, нет необходимости держать div контейнер в компоненте, т.к. стиль скрытия применяется к хосту. С ролью контейнера для отображения popup может справиться хост-элемент компонента, нужно лишь в файле стилей поменять `.popup-container` -> `:host`, после чего `<div class="popup-container">` окончательно потеряет свою полезность

2023-01-26 04:47 UTC, closed without merging