Lecture 2
Letto228/Angular-learnjs-121222 pull request #36
Opened 2022-12-20 13:20 UTC by IlyaPershin

2022-12-21 07:15 UTC, Letto228 requested changes
Привет
Оставил пару комментариев, посмотри пожалуйста. Еще есть общий кейс по МР - давай уберем комментарии из компонента карточки товара, немного портит продовый код)

2022-12-21 07:15 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +			>Рейтинг: {{ rating }}/5</mat-card-subtitle
Преттиер так строки отформатировал?

2022-12-21 07:15 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +	readonly id = productMock._id;
А нам нужно столько свойств?
Я бы предложил использовать только одно - `readonly productMock = productMock` и из этого объекта тянуть свойства в шаблоне.

Почему столько свойств считаю плохой практикой - затратно и загрязняет компонент: при каждом новом значении, которое захотим вывести - будет создаваться новое свойство, и так мы можем 20-30 строк(в теории) потратить только на свойства, которые будут использоваться в шаблоне(а когда будем работать с Observable - ситуация усугубится). В то же время, можно обойтись одним свойством(в котором хранится сущность) и получить из него данные в шаблоне. Данный подход не испортит читаемость и чистоту кода, в нашем случаи. Если будут сложные кейсы для вычисления какого-то значения или длинные, сложночитаемые цепочки, то там будем создавать гетеры или свойства, но пока такого нет

2022-12-21 07:15 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +		// event.stopPropagation();
Почему закомментировал, данная функцианальность нам необходима

2022-12-22 06:05 UTC, IlyaPershin commented on src/app/products-list/product-card/product-card.component.html
> +			>Рейтинг: {{ rating }}/5</mat-card-subtitle
Да, если оставить тег и его содержание в одной строке

2022-12-22 06:09 UTC, IlyaPershin commented
Замечания которые получил исправил

2022-12-22 06:59 UTC, Letto228 approved these changes
Все исправления увидел - супер!

Увидел еще одно не корректное форматирование, пометил его. В целом, апрувнул МР, по этому данный комментарий на будущее.

2022-12-22 06:59 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +		<mat-card-title class="product-name">{{
Тут видимо тоже преттиер постарался

2022-12-22 06:59 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +		<mat-card-title class="product-name">{{
Интерполяция становится менее заметной, по этому нужно стремиться к такой записи:
```html
<mat-card-title class="product-name">
    {{productMock.name}}
</mat-card-title>
```
В общем `{{...}}` стоит считать неразрывным целым, чтобы быстро его идентифицировать в шаблоне и сохранить его чистоту. А при той записи, что сейчас, можно подумать, что `productMock.name` это чистый текст который будет вставлен в шаблон, потому что контекст интерполяции размывается

2022-12-22 06:59 UTC, closed without merging