added product card
Letto228/Angular-learnjs-121222 pull request #38
Opened 2022-12-20 21:01 UTC by sulakin

2022-12-20 21:03 UTC, sulakin commented
добавление карточки в последнем коммите
https://github.com/Letto228/Angular-learnjs-121222/pull/38/commits/87ce8d382e61cd3c7c1aecff9467fb224e06b4d9

2022-12-21 06:51 UTC, Letto228 requested changes
Привет
Посмотрел - оставил пару комментариев, посмотри пожалуйста

2022-12-21 06:51 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +      min="0" max="{{card.images.length}}"
Почему решил использовать интерполяцию в `max="{{card.images.length}}"`? По смыслу, binding больше подходит - мы связываем атрибут `max` с значением `card.images.length`

2022-12-21 06:51 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +      (change)="sliderHandler($event)"
Есть практика: обработчики писать с префиксом `on` - `onImageSliderChange` например. Порекомендовал бы придерживаться ее, позволяет проще ориентироваться в коде

2022-12-21 06:51 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +      <mat-icon aria-hidden="false" aria-label="Example home icon" fontIcon="hotel_class"></mat-icon>
Давай придем к единому стилю использования `mat-icon` компонента, чтобы повысить чистоту кода: либо используем `fontIcon` свойство для указания иконки, либо указываем используемую иконку между тегами компонента(такой способ применения используется для `payments` иконки)

2022-12-21 06:51 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +  public activeImageSrc: string;
Тут я предложил бы такую запись:
```
public activeImageSrc = this.card.images[0].url;
```

Считаю, что воспринимать ее проще и код чище, т.к. в одном месте объявляем свойство и тут же видим какое в нем значение лежит на старте. В следствии таких изменений можно удалить конструктор в классе

2022-12-21 06:51 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +  sliderHandler(event: any) {
`any` тип загрязняет код и сводит типизацию TS на нет. По этому предложил бы более строготипизировать метод - `event: Event`

2022-12-21 06:51 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +    this.activeImageSrc = this.card.images[event.target.ariaValueText].url;
Считаю, что данную строку тоже можно разгрузить и сделать более читаемой, т.к. не посмотрев на шаблон, где используется функция - сложно понять откуда и какое значение она берет(особенно когда отойдем от контекста данного метода). Что предлагаю: добавить переменные с типизацией и в данной стоке только доставать из массива изображений url по необходимому индексу.

Тут набросал примерную реализацию, как это мне видится:
```ts
  sliderHandler(event: Event) {
    const sliderValue = (event.target as HTMLInputElement).ariaValueText;
    const imageIndex = sliderValue === null ? Number(sliderValue) : 0;

    this.activeImageSrc = this.card.images[imageIndex].url;
}
```

2022-12-21 07:44 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.html
> +      min="0" max="{{card.images.length}}"
поправил

2022-12-21 07:44 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.html
> +      (change)="sliderHandler($event)"
притащил из реакта) поправил

2022-12-21 07:45 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.html
> +      <mat-icon aria-hidden="false" aria-label="Example home icon" fontIcon="hotel_class"></mat-icon>
все привел к упрощенному виду

2022-12-21 07:47 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.ts
> +  public activeImageSrc: string;
поправил, но там по хорошему еще нужно проверку делать что фото вообще есть. скорее всего нужен вспомогательный метод, который это будет делать и его как раз запускать в конструкторе или в ngOnInit

2022-12-21 07:48 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.ts
> +  sliderHandler(event: any) {
заменил на Event

2022-12-21 07:55 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.ts
> +    this.activeImageSrc = this.card.images[event.target.ariaValueText].url;
поправил. только проверку на null убрал, иначе тернарка в обратную работает, можно было строгое отрицание поставить

2022-12-22 07:03 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +  public activeImageSrc: string;
Можно использовать optional chaining и если фото нет, то в свойстве будет просто лежать `undefined`

2022-12-22 07:07 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +    this.activeImageSrc = this.card.images[event.target.ariaValueText].url;
Да, видимо поторопился)

2022-12-22 07:08 UTC, Letto228 approved these changes
Прошелся еще раз по МР, выглядит все бодро - апруваю

2022-12-22 07:08 UTC, closed without merging