feat: реализован функционал карточки товара
Letto228/Angular-learnjs-121222 pull request #46
Opened 2022-12-22 13:37 UTC by DmChupin

2022-12-23 05:48 UTC, Letto228 requested changes
Нихао)
Все 🔥 , есть пару замечаний по форматированию кода, посмотри, пожалуйста

2022-12-23 05:48 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +		#nav
Не увидел, где бы мы использовали данную шаблонную переменную, давай уберем ее

2022-12-23 05:48 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +		return {
Давай сделаем без `return`, так, думаю, будет поприятней
```ts
readonly images = this.card.images.map((img: IProductImage) => ({
			image: img.url,
			thumbImage: img.url,
}));
```

2022-12-23 05:48 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +			>Отзывы : {{ card.feedbacksCount }}</mat-card-subtitle
Prettier, к огромному сожалению, не всегда валидно может обработать длинную строку, особенно заметно это в HTML. Тут `>` и `Отзывы` не разделены пробелом, по этому prettier посчитал, что их нужно перенести вместе.
Давай исправим форматирование - контент заключим между тегами на разных строках:
```html
<mat-card-subtitle align="end">
    Отзывы : {{ card.feedbacksCount }}
</mat-card-subtitle>
```

2022-12-24 21:47 UTC, DmChupin commented
Привет!
Все замечания поправил.

2022-12-25 08:45 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +			>Отзывы : {{ card.feedbacksCount }}</mat-card-subtitle
Вот тут, кажется, не до конца подправил, обрати внимание, в будущем, пожалуйста

2022-12-25 08:49 UTC, Letto228 approved these changes
Огонь, увидел
Правда по форматированию HTML один недочет остался https://github.com/Letto228/Angular-learnjs-121222/pull/46#discussion_r1056919540

В целом, комментарий по форматированию кажется не критичным, просто возьмем его на заметку с прицелом на будущее. Если же отформатировано так, как ты и планировал - дай знать, обсудим)

2022-12-25 08:50 UTC, closed without merging

2022-12-25 09:27 UTC, DmChupin commented
Форматирование там тоже поправлено, может просто не туда глянул куда-то?
![image](https://user-images.githubusercontent.com/32493372/209462939-f96a26b8-f05c-49ab-a9e0-2c34b56a4ad0.png)