feat: lesson-3-dz
Letto228/Angular-learnjs-121222 pull request #49
Opened 2022-12-24 11:57 UTC by nigavshin

2022-12-25 08:39 UTC, Letto228 requested changes
Привет!
Все понравилось 🔥
Есть один вопрос по поводу атрибута, посмотри, пожалуйста

2022-12-25 08:39 UTC, Letto228 commented on src/app/app.component.html
> +<app-products-list onProd></app-products-list>
А зачем данный атрибут?

2022-12-26 05:47 UTC, nigavshin commented on src/app/app.component.html
> +<app-products-list onProd></app-products-list>
Сорри, убрал))

2022-12-26 06:03 UTC, Letto228 approved these changes
Огонь, МР апрувнут!

2022-12-26 06:03 UTC, closed without merging