homework for lesson 3
Letto228/Angular-learnjs-121222 pull request #50
Opened 2022-12-25 10:17 UTC by sulakin

2022-12-25 10:19 UTC, sulakin commented
ДЗ в последнем коммите https://github.com/Letto228/Angular-learnjs-121222/pull/50/commits/46503e95fc5066918865e3b5af54616762594697

2022-12-26 05:26 UTC, Letto228 requested changes
Привет!
Увидел коммит, спасибо. Оставил один комментарий по стилю кода и один комментарий по логике, посмотри, пожалуйста

2022-12-26 05:26 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +    if (id) console.log(id);
Давай полностью дописывать `if` блоки, нам пару символов добавить ничего не стоит, а код будет чище

2022-12-26 05:26 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +  ngAfterContentInit() {
Почему решил `activeImageSrc` проставлять в этом хуке?

2022-12-26 10:15 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.ts
> +    if (id) console.log(id);
поправил. но вопрос сильно спорный

2022-12-26 10:18 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.ts
> +  ngAfterContentInit() {
почитал доку, хук показался подходящим. стоит какой то другой использовать?

2022-12-27 05:53 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +    if (id) console.log(id);
Давай обсудим его: почему считаешь, что блок лучше не ставить?

2022-12-27 06:07 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +  ngAfterContentInit() {
Хук `ngAfterContentInit` используется для информирования об окончании проецирования переданного внешнего контента во view компонента. Здесь речь идет про view контент, который был помещен между тэгами хост-элемента компонента.
Есть еще один нюанс: `Input` свойство может меняться, а хук `ngAfterContentInit` отрабатывает только один раз. То есть если набор изображений в инпуте вдруг изменится, то компонент этого даже не отобразит

Если сформировать требования: нужно установить значение `activeImageSrc` тогда, когда пришла карточка в `Input` свойсвто, при чем, при последующем изменении инпута, нужно заново устанавливать значение по новым данным. Для этих целей отлично подойдет хук `ngOnChanges`, он позволит отследить изменение инпута и среагировать на него.

2022-12-27 15:28 UTC, sulakin commented on src/app/products-list/product-card/product-card.component.ts
> +  ngAfterContentInit() {
понял, заменил.

2022-12-29 15:40 UTC, Letto228 approved these changes
Огонь, апрувнул
Если будет желание обсудить https://github.com/Letto228/Angular-learnjs-121222/pull/50#discussion_r1057176716 - можешь писать в Discord, с радостью пообсуждаю

2022-12-29 15:40 UTC, closed without merging