feat: inputs and outputs
Letto228/Angular-learnjs-121222 pull request #52
Opened 2022-12-25 12:04 UTC by mrfrac

2022-12-26 05:41 UTC, Letto228 requested changes
Привет
Оставил один комментарий по хорошей практике, посмотри, пожалуйста. В остальном все cool

2022-12-26 05:41 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		if (this.product && this.product.images.length > 0) {
Давай вынесем выражение(`this.product && this.product.images.length > 0`) в константу перед `if`. Оно вроде бы и не сложное, но в целом, хорошей практикой считается не передавать в `if` выражения, исключениями могут быть простые кейсы: инвертирование значения (`!this.product`)

2022-12-26 05:41 UTC, Letto228 commented on src/app/modules/products-list/products-list.component.html
> +	<li *ngFor="let product of productsList">
`*ngFor` - бьешь на опережение)

2022-12-26 06:45 UTC, mrfrac commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		if (this.product && this.product.images.length > 0) {
Да, в целом с замечанием согласен! Но мне кажется это не тот случай: после того, как вынес условие в отдельную перменную, TS перестал доверять записи `this.product.images`, т.е. пришлось снова писать `this.product?.images[0]?.url`. Возможно проще было бы сделать сразу return тернарного оператора! 

И по другому сделал вывод изображения в шаблоне! Посмотри пожалуйста! Не круто так делать в шаблонах?

2022-12-27 07:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		if (this.product && this.product.images.length > 0) {
Есть 2 типа Angular разработчиков: первые - несут по максимуму логики в шаблон, вторые - по максимуму разгружают шаблон от логики.
Я отношусь ко второму типу людей, по этому `product && product.images ? product.images[0].url : ''` мне кажется сложным для шаблона. Если бы использовали optional chaining, читалось бы проще - либо необходимая цепочка есть, либо ее нет, по этому противоречий нет, но используя тернарник - появляется некоторая логика(если есть продукт - верни то, если продукта нет - верни другое), что воспринимается в контексте шаблона сложнее, усугубляется еще тем, что в условии тернарника тоже идет выражение

По этому я склоняюсь к тому, что эта логика должна быть в компоненте, а грузить шаблон логикой - это, да, не  круто)

2022-12-27 07:13 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		if (this.product && this.product.images.length > 0) {
Конечно есть тонкая грань с пайпами, но это другая история

2022-12-27 07:14 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		if (this.product && this.product.images.length > 0) {
По типизации сегодня вечером посмотрю и отпишусь

2022-12-29 15:41 UTC, Letto228 commented
К сожалению еще не добрался, постараюсь к 31 просмотреть

2023-01-10 06:33 UTC, Letto228 commented
Привет!
Не смог таки я победить типизацию(
Последнее к чему я пришел - тернарник. С константами было бы лучше в плане читаемости, но данный тернарник тоже выглядит не грязно(т.е. в пределах допустимого)
```ts
getImageUrl(): string {
	return this.product && this.product.images.length > 0
		? this.product.images[0].url
		: ''
}
```

2023-01-10 06:35 UTC, Letto228 requested changes
Отписался по типизации в комментарии https://github.com/Letto228/Angular-learnjs-121222/pull/52#issuecomment-1376795864

2023-01-10 09:33 UTC, mrfrac commented
> Привет! Не смог таки я победить типизацию( Последнее к чему я пришел - тернарник. С константами было бы лучше в плане читаемости, но данный тернарник тоже выглядит не грязно(т.е. в пределах допустимого)
> 
> ```ts
> getImageUrl(): string {
> 	return this.product && this.product.images.length > 0
> 		? this.product.images[0].url
> 		: ''
> }
> ```

Доработал реквест!

В целом посыл понятен. Сам на практике использую константы в таких случаях, когда условие в if большое! Что-то типа (далее фантазия):
```ts
const hasPermission = employee.isManager() && employee.hasPermission("somePermission");
const isContractValid = this.contract.isValid() && this.contract.Status = ContractStatuses.Signed;

if (hasPermission && isContractValid) {
    // do something
}
```

2023-01-11 04:51 UTC, Letto228 commented
> > Привет! Не смог таки я победить типизацию( Последнее к чему я пришел - тернарник. С константами было бы лучше в плане читаемости, но данный тернарник тоже выглядит не грязно(т.е. в пределах допустимого)
> > ```ts
> > getImageUrl(): string {
> > 	return this.product && this.product.images.length > 0
> > 		? this.product.images[0].url
> > 		: ''
> > }
> > ```
> 
> Доработал реквест!
> 
> В целом посыл понятен. Сам на практике использую константы в таких случаях, когда условие в if большое! Что-то типа (далее фантазия):
> 
> ```ts
> const hasPermission = employee.isManager() && employee.hasPermission("somePermission");
> const isContractValid = this.contract.isValid() && this.contract.Status = ContractStatuses.Signed;
> 
> if (hasPermission && isContractValid) {
>     // do something
> }
> ```

Это очень хорошая практика👍
P.S. `this.contract.Status = ContractStatuses.Signed` - тут же `===` должно было быть?)

2023-01-11 04:54 UTC, Letto228 approved these changes
Огонь, апрув

2023-01-11 04:54 UTC, closed without merging