feat: add Input and Output for product card
Letto228/Angular-learnjs-121222 pull request #55
Opened 2022-12-25 19:35 UTC by dkruglova

2022-12-26 06:01 UTC, Letto228 requested changes
Привет!
Оставил два комментария, посмотри, пожалуйста

2022-12-26 06:01 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() buyProduct = new EventEmitter<Event>();
Давай немного доработаем `@Output`. Думаю, в нем стоит прокидывать не событие `Event`, вряд ли в обработчике `productBuy` события он будет полезен

2022-12-26 15:22 UTC, dkruglova commented on src/app/modules/products-list/product-card/product-card.component.html
> +			[src]="product ? product.images[0].url : undefined"
Исправила

2022-12-26 15:23 UTC, dkruglova commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() buyProduct = new EventEmitter<Event>();
Доработала. Надеюсь правильно поняла )) Пока не стала никакое значение прокидывать

2022-12-27 06:29 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +			[src]="product ? product.images[0].url : undefined"
Да, все именно так!

Единственное, в чем мы сейчас пострадали - `productPhotoUrl` стал статичным свойством(OnInit вызывается только 1 раз), а `@Input() product` - остается динамичным, т.е. возможна ситуация, когда инпут поменялся, а изображение осталось прежним.

Давай попробуем посмотреть в сторону хука `OnChanges` - он должен сюда отлично подойти

2022-12-27 06:31 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() buyProduct = new EventEmitter<Event>();
Да, все судя по всему - правильно)

А почему не стала пробрасывать никакое значение? Обработчику, наверное, было бы хорошо знать `id` продукта, который должен попасть в корзину

2022-12-29 16:59 UTC, dkruglova commented on src/app/modules/products-list/product-card/product-card.component.html
> +			[src]="product ? product.images[0].url : undefined"
Да, действительно, OnChanges лучше подходит. Исправила.

2022-12-29 17:02 UTC, dkruglova commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() buyProduct = new EventEmitter<Event>();
Сначала подумала про id, но пока никакой обработки данных в buyProduct  не было предусмотрено, поэтому не стала ничего передавать. 
Доработала :)

2022-12-30 16:11 UTC, Letto228 approved these changes
Супер, с уверенностью ставлю апрув!

2022-12-30 16:11 UTC, closed without merging