feat: adding to cart
Letto228/Angular-learnjs-121222 pull request #56
Opened 2022-12-26 12:58 UTC by sergey-gonchar

2022-12-27 07:08 UTC, Letto228 requested changes
Привет!
Здорово с корзиной придумал)
Оставил пару комментариев по логике, посмотри, пожалуйста

2022-12-27 07:08 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		this.isProductEmpty = this.productEmpty;
По `isProductEmpty` есть пару комментариев:
1. Для инициализации `isProductEmpty` используется `OnInit`, но далее свойство `isProductEmpty` никак не обновляется. К чему я это - если изменится инпут и в него поступят данные, то внутреннее свойство `isProductEmpty` никак не обновится. Я бы предложил для таких целей воспользоваться `OnChanges` хуком
2. В данном случаи выделение геттера кажется избыточным, т.к. в классе компонента получаем два свойства, которые описывают одно и то же состояние компонента - пустоту. Что предлагаю: убрать геттер, ЛИБО навесить `@HostBinding('class.empty')` на сам геттер `productEmpty` - в таком случаи можно уйти от отдельного свойства `isProductEmpty`(но нейминг геттера я бы изменил на `isProductEmpty`).

2022-12-27 15:33 UTC, sergey-gonchar commented on src/app/modules/products-list/products-list.component.ts
> +		this.products = [...this.products, ...[productMock, productMock, productMock]];
поправил

2022-12-27 15:33 UTC, sergey-gonchar commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() addedToCart: EventEmitter<IProduct> = new EventEmitter<IProduct>();
Не хочу чтоб в корзину могли попадать undefined, добавил для этого условие

2022-12-27 15:33 UTC, sergey-gonchar commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		this.isProductEmpty = this.productEmpty;
понравилась мысль навесить на геттер, сделал

2022-12-29 15:45 UTC, Letto228 approved these changes
Огонь, апрувнул
Увидел импорт не используемый, отписался по нему. Для ДЗ считаю не критично - по этому МР закрою

2022-12-29 15:45 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +import { Component, EventEmitter, HostBinding, Input, OnChanges, OnInit, Output } from '@angular/core';
`OnInit` не используется, держать МР из-за этого не будем, но поинт на будущее

2022-12-29 15:45 UTC, closed without merging