feat: popup component (lecture 4)
Letto228/Angular-learnjs-121222 pull request #59
Opened 2022-12-27 11:01 UTC by mrfrac

![image](https://user-images.githubusercontent.com/19538736/209657177-9af7ed03-9b80-493e-b255-00e350e4a4f8.png)

2022-12-29 15:48 UTC, Letto228 requested changes
Привет
Все супер, чисто и лаконично, но один кейс не учли, посмотри, пожалуйста

2022-12-29 15:48 UTC, Letto228 commented on src/app/shared/popup/popup-host/popup-host.component.ts
> +	@Input() set popupTemplate(template: TemplateRef<unknown>) {
А если в попап не придет template, а придет `undefined` в тех кейсах, когда попап захотят закрыть? Давай рассмотрим кейс и для `undefined`

2023-01-03 12:03 UTC, mrfrac commented on src/app/shared/popup/popup-host/popup-host.component.ts
> +	@Input() set popupTemplate(template: TemplateRef<unknown>) {
Доработал (если я правильно понял кейс с undefined).

2023-01-08 20:33 UTC, Letto228 requested changes
Увидел последние изменения изменения - все гуд!

2023-01-08 20:33 UTC, Letto228 commented on src/app/shared/popup/popup-host/popup-host.component.ts
> +	@Input() set popupTemplate(template: TemplateRef<unknown>) {
Почти, думаю, что стоит все таки контейнер чистить при любых обстоятельствах, т.е. при получении `undefined` - мы должны уничтожить view; при получении `tempalte` - вставить `view`

2023-01-08 20:35 UTC, Letto228 approved these changes

2023-01-08 20:35 UTC, closed without merging