feat: Product card component added
Letto228/Angular-learnjs-121222 pull request #60
Opened 2022-12-27 18:32 UTC by Dimash77777

2022-12-30 16:21 UTC, Letto228 requested changes
Привет
Есть одна не доработка в шаблоне, посмотри, пожалуйста. В остальном все гуд!

2022-12-30 16:21 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +		<button mat-button click="onItemBuy($event)" class="property">
Кажется, что недоработан обработчик клика, запись `click="onItemBuy($event)"` не совсем корректна

2023-01-05 12:29 UTC, Dimash77777 commented on src/app/products-list/product-card/product-card.component.html
> +		<button mat-button click="onItemBuy($event)" class="property">
Спасибо, согласен, ошибочка вышла ) Поправил.

2023-01-08 20:36 UTC, Letto228 approved these changes
Огонь! От меня апрув 👍

2023-01-08 20:36 UTC, closed without merging