feat: add popup-contaner component
Letto228/Angular-learnjs-121222 pull request #62
Opened 2022-12-28 06:09 UTC by ValentinYoushkevich

2022-12-28 14:43 UTC, sergey-gonchar commented on src/app/shared/popup/popup/popup-contaner/popup-contaner.component.ts
> +	ngOnInit() {
значение в инпуте может меняться, тут наверное лучше использовать хук ngOnChanges

2022-12-29 16:16 UTC, Letto228 requested changes
Привет!
Есть один комментарий не большой по `ngOnChanges`, посмотри, пожалуйста

2022-12-29 16:16 UTC, Letto228 commented on src/app/shared/popup/popup/popup-contaner/popup-contaner.component.ts
> +	ngOnChanges() {
Давай сразу будем вырабатывать привычку проверять изменения полей в `OnChanges`. Сейчас, если у тебя добавится новый инпут, назовем его `text`, то есть вероятность, что лишний раз отработает `OnChanges` на изменение `text` и без необходимости будет очищен контейнер и заново вставлен шаблон, а это не совсем круто.

Давай добавим проверку на изменение инпута при помощи `SimpleChanges` в аргументе `ngOnChanges` метода.

А ее я предложил бы посмотреть в сторону сеттера для инпута, кажется очень удобным в нашей ситуации

2023-01-01 09:22 UTC, ValentinYoushkevich commented
> Думаю стоит расположить хост по верх всего приложения и регулировать его прозрачность за счет `pointer-events` стиля, а контент в попапе распологать по центру и с `position: relative`

Вот эту часть не понял вообще.

2023-01-01 09:25 UTC, ValentinYoushkevich commented on src/app/shared/popup/popup/popup-contaner/popup-contaner.component.ts
> +	ngOnChanges() {
тут согласен, поправил.
На счет сетера специально его не пользовал потому как там все понятно, пошел тем путем где мне было менее очевидно, просто чтобы лучше разобраться

2023-01-09 06:16 UTC, Letto228 commented
https://github.com/Letto228/Angular-learnjs-121222/pull/62#issuecomment-1368396927

Соль в чем, для отображения popup над контентом, тебе приходится задавать стили для контента popup - https://github.com/Letto228/Angular-learnjs-121222/pull/62/files#diff-d4426aa193c344b21b37d8bb6851ce2a291ca141f7fbf82cfb77d78998c8efe9R1

А сама идея `popup-host` компонента заключалась в том, чтобы любой шаблон корректно отображался в `popup-host` компоненте, то есть все стили отображения контента над приложением должны ложиться на этот компонент. Получается, что хост компонент должен быть развернут на экран пользователя, и контент в нем должен располагаться через `position: relative`. Но, в таком случае, `popup-host` перекроет весь контент приложения, т.е. его нужно будет скрывать и для этого я предложил использовать `pointer-events` свойство, чтобы сделать хост прозрачым для кликов и т.д. Есть и другие способы, например - использовать `display: none` и т.д.

На лекции по этому ДЗ мы не изучали декоратор `@HostBinding`, хотя он тут бы очень пригодился, но можно обойтись и без него, для этого стоит оставить стили `popup-host` как есть и добавить внутрь `popup-host` шаблона div обертку внутри него, в div обертке, соответсвенно будет располагаться контент, и на обертку будет навешиваться необходимые стили для расположения хоста на странице: `position: absolute/fixed` и т.д.

```html
<div class="popup-host-container" [class.hide]="template">
    <ng-container #popupContainer></ng-container>
</div>
```
```css
.popup-host-container {
    position: absolute;
    top: 0;
    bottom: 0;
    ...
}

.hide {
    display: none; // как пример
}
```

А вот моя реализация через `HostBinding` и `pointer-event` - https://github.com/Letto228/Angular-learnjs-121222/pull/67/files


Надеюсь тут понятней получилось расписать. Если понятней не стало, или есть доп вопросы, напиши, пожалуйста, в дискорде. Скооперируемся с тобой и разберем все по полочкам

2024-05-17 05:15 UTC, closed without merging