'lesson-3'
Letto228/Angular-learnjs-121222 pull request #63
Opened 2022-12-28 09:56 UTC by IlyaPershin

2022-12-30 17:03 UTC, Letto228 requested changes
Привет!
Заметил несколько моментов, посмотри, пожалуйста. Если будут вопросы - можно написать их тут, или в Discord(так, кажется, пооперативней будет)

2023-01-02 10:33 UTC, IlyaPershin commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	ngOnChanges() {
Тогда я думаю лучше будет заменить на ngOnInit чтобы отработало только при инициализации

2023-01-02 10:55 UTC, IlyaPershin commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		if (this.activeImageIndex == 0 && this.product?.images.length){
Решил заменить эти 2 метода на 1 универсальный и более читаемый

2023-01-02 10:56 UTC, IlyaPershin commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		return Boolean(this.product && this.product?.rating >= starIndex);
Согласен, исправил

2023-01-02 10:56 UTC, IlyaPershin commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	  this.productClick.emit(event);
Согласен, исправил

2023-01-08 20:52 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +		<button mat-icon-button (click)="changeImage(-1)">
Такие числа называют магическими)
Лучше вынести их в свойство-константу с говорящим именем

2023-01-08 20:52 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	ngOnChanges() {
Да, в нашем кейсе `OnInit` хук для этого подойдет, т.к. продукт изменяться не будет.
Но, если предполагается, что `product` может быть координально изменен или могут поменяться изображения в нем, то стоит вернуться к `OnChanges` и сбросывать параметры `activeImageUrl` и `activeImageIndex`, иначе попадем в такую ситуацию: изображения у продукта изменилось, а отображается все равно старое изображение, т.к. `activeImageUrl` не изменился.

2023-01-08 20:58 UTC, Letto228 requested changes
Супер! Оставил еще пару комментариев, один по логике(на порассуждать) и два по хорошим практикам, посмотри, пожалуйста

2023-01-08 20:58 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		let imagesLength : number = this.product ? this.product?.images.length : 0;
Не вижу, чтобы эта переменная изменялась после объявления. Давай сделаем ее константой

2023-01-11 07:47 UTC, IlyaPershin commented
Исправил все замечания

2023-01-12 04:43 UTC, Letto228 approved these changes
Отлично! Вопросов нет - апрув

2023-01-12 04:43 UTC, closed without merging