feat: lecture 4dz
Letto228/Angular-learnjs-121222 pull request #64
Opened 2022-12-28 13:32 UTC by nigavshin

2022-12-29 16:27 UTC, Letto228 commented
Привет!
Увидел твой комментарий в коде, давай отдельно свяжемся в Discord и попробуем разобраться.

2023-01-07 12:37 UTC, nigavshin commented
Кажется, я разобрался с этим. Если что, у меня появятся вопросы, я обязательно их задам.

2023-01-15 13:42 UTC, Letto228 requested changes
Привет!
Все гуд, есть пару небольших комментариев, посмотри пожалуйста

2023-01-15 15:41 UTC, nigavshin commented on src/app/shared/popup/popup-host/popup-host.component.ts
> +	@ViewChild('template', { read: ViewContainerRef, static: true })
готово

2023-01-15 15:41 UTC, nigavshin commented on src/app/shared/popup/popup-host/popup-host.component.ts
> +	@Input() set popupTemplate(template: TemplateRef<unknown>) {
готово

2023-01-17 05:58 UTC, Letto228 approved these changes
Good - апрув

2023-01-17 05:58 UTC, closed without merging