feat: dz-4.popup
Letto228/Angular-learnjs-121222 pull request #65
Opened 2022-12-28 14:38 UTC by sergey-gonchar

2022-12-31 10:18 UTC, Letto228 requested changes
Привет
Огонь! Хороший компонент получился)
Есть 2 нюанса которые смущают, давай разберем:
1. Я бы рассмотрел кейс, когда в `popupTemplate` приходит `undefined`. В теории такой кейс возможен, например, когда будет сбрасываться состояние переменной в которой хранится `template` в родительском компоненте. Если же в твоей архитектуре такого кейса нет, то тогда можно не учитывать кейс с `undefined`
2. В `tempalte` может быть прописан компонент, соответственно, при создании view на основе template - создастся и компонент используемый в нем. Вот в чем соль, при закрытии попапа, ожидаешь ли ты, что компонент будет уничтожен, что у него отработает хук `OnDestroy`, который выполнит отписки от подписок в компоненте(если они, конечно же там есть)?
Мне как раз таки кажется, что при закрытии попапа стоит уничтожать вставленный view, так будет более корректно, т.к. нет смысла держать рабочий компонент, раз попап с ним закрыли.
Возможно, у тебя попап используется для кейсов в которых обычное скрытие view, без его уничтожения, это подходящее решение, по этому нужны твои комментарии

Буду ждать твоего ответа)

2023-01-03 06:17 UTC, sergey-gonchar commented
> 1. Я бы рассмотрел кейс, когда в `popupTemplate` приходит `undefined`. В теории такой кейс возможен, например, когда будет сбрасываться состояние переменной в которой хранится `template` в родительском компоненте. Если же в твоей архитектуре такого кейса нет, то тогда можно не учитывать кейс с `undefined`

Этот момент поправил

2023-01-03 06:20 UTC, sergey-gonchar commented
>    Мне как раз таки кажется, что при закрытии попапа стоит уничтожать вставленный view, так будет более корректно, т.к. нет смысла держать рабочий компонент, раз попап с ним закрыли.

Логично. Добавил очистку viewContainer при закрытии попапа. 

P.S. Посмотри пожалуйста, я немного отрефакторил компонент попапа. но не могу понять лучше стало или хуже и что еще поправить?

2023-01-08 21:17 UTC, Letto228 approved these changes
Вообще красота, мне понравилось👍)
Единственный комментарий - к тернарнику, но он рекомендационный, на поразмыслить, по этому, ставлю апрув и закрываю МР

2023-01-08 21:17 UTC, Letto228 commented on src/app/shared/popup-host/popup-host.component.ts
> +		this.opened ? this.open() : this.viewContainer?.clear();
Я придерживаюсь правила по поводу тернарников - использую их только для возвращаемых значений, т.е. в тех кейсах, когда возвращаемое значение из тернарника куда либо передается или сохраняется. Если же возвращаемое из тернарника значение игнорируется(как в нашем случае), то использую `if` блок, для разделения кейсов.

2023-01-08 21:17 UTC, closed without merging