'lesson-4'
Letto228/Angular-learnjs-121222 pull request #66
Opened 2022-12-29 11:20 UTC by IlyaPershin

2022-12-31 10:37 UTC, Letto228 requested changes
Нихао)
Оставил пару комментариев, посмотри, пожалуйста.
Есть еще общий комментарий по логике popup'a:
В `tempalte` может быть прописан компонент, соответственно, при создании view на основе `template` - создастся и компонент используемый в нем. Вот в чем соль, при закрытии попапа, ожидаешь ли ты, что компонент будет уничтожен, что у него отработает хук `OnDestroy`, который выполнит отписки от подписок в компоненте(если они, конечно же там есть)?
Мне как раз таки кажется, что при закрытии попапа стоит уничтожать вставленный view, так будет более корректно, т.к. нет смысла держать рабочий компонент, раз он не используется.
Возможно, у тебя попап используется для кейсов в которых обычное скрытие view, без его уничтожения, тогда это подходящее решение. По этому нужны твои комментарии, буду ждать твоего ответа

2022-12-31 10:37 UTC, Letto228 commented on src/app/app.component.ts
> +	@ViewChild('popup')
А элемент с шаблонной переменной `popup` не статичен? Кажется, что он на странице всегда `<app-popup [popupTemplate]="popupTemplate" #popup></app-popup>`

2022-12-31 10:37 UTC, Letto228 commented on src/app/app.component.ts
> +	@ViewChild('popupTextInput', {read: ElementRef, static: false})
Если используется `static: false`, то это свойство можно не писать, такое значение используется по умолчанию.
И возникает вопрос такой же как и к `@ViewChild('popup')` выше: почему `static: false`?

2022-12-31 10:37 UTC, Letto228 commented on src/app/app.component.ts
> +		if (!this.popup?.visible) {
Вопрос, конечной, холиварный, но я бы рекомендовал подход с ранним ретерном, считаю его более чистым и гибким, в целом он больше подходит для написания чистого кода. Если хочется чуть поподробнее рассуждения на эту тему  - дай знать, отдельно напишу с примером

2022-12-31 10:37 UTC, Letto228 commented on src/app/app.component.ts
> +			if (this.popupText && text != '') {
Я бы чуть изменил проверку, думаю достаточно проверить, что строка не пустая, для этого можно использовать `text` вместо `text != ''`('' - будет false при преобразовании в boolean, а любая другая строка - true)
Как я это условие вижу: `const needOpenPopup = this.popupText && text`

2022-12-31 10:37 UTC, Letto228 commented on src/app/components/sidenav/sidenav.component.less
> +	height: 20%;
Почему так сжал?

2022-12-31 10:37 UTC, Letto228 commented on src/app/shared/popup/popup.component.ts
> +  @Input() set popupTemplate(template: TemplateRef<any>) {
Я бы рассмотрел кейс, когда в `popupTemplate` приходит `undefined`. В теории такой кейс возможен, например, когда будет сбрасываться состояние переменной в которой хранится `template` в родительском компоненте. Если же в твоей архитектуре такого кейса нет, то тогда можно не учитывать кейс с `undefined`

2023-01-06 12:36 UTC, IlyaPershin commented on src/app/components/sidenav/sidenav.component.less
> +	height: 20%;
просто чтобы попап не прятался вниз экрана

2023-01-06 13:06 UTC, IlyaPershin commented on src/app/app.component.ts
> +		if (!this.popup?.visible) {
Я понимаю, сам не люблю как выглядит ходукен. Но иногда не сразу додумываюсь как сделать более читаемо.

2023-01-06 13:08 UTC, IlyaPershin commented
Не очень понимаю как сделать уничтожение темплейта. Можете скинуть какой-либо пример подробного?

2023-01-10 06:04 UTC, Letto228 commented
> Не очень понимаю как сделать уничтожение темплейта. Можете скинуть какой-либо пример подробного?

Можно воспользоваться уже знакомой практикой - `this.viewContainer.clear();` и в контейнере уничтожатся все view. Так же можно точечно уничтожить view по индексу в контейнере(https://angular.io/api/core/ViewContainerRef#remove), но нам этого делать нет необходимости, т.к. в контейнере всего одно view.

2023-01-11 08:08 UTC, IlyaPershin commented
Доработал отображение и очистку через clear

2023-01-12 04:57 UTC, Letto228 requested changes
Гуд, подсветил еще пару нюансов, финальных, посмотри, пожалуйста

2023-01-12 04:57 UTC, Letto228 commented on src/app/components/sidenav/sidenav.component.less
> +	height: 20%;
Подразумевается, что popup будет располагаться над всем контентом на странице, по этому стоит вернуть высоту и добавить `position: fixed` к `div` контейнеру в popup-host

2023-01-12 04:57 UTC, Letto228 commented on src/app/shared/popup/popup.component.ts
> +  @Input() set popupTemplate(template: TemplateRef<any>) {
Тут в типизации, давай тоже добавим `undefined` т.к. его значение тоже ожидаемо

2023-01-12 04:57 UTC, Letto228 commented on src/app/shared/popup/popup.component.ts
> +    } else {
Я бы рекомендовал вместо `if/else` использовать ранний ретерн, с ним код становится чище и гибче:
```ts
if (template && !this.visible) {
      this.viewContainer.createEmbeddedView(template);
      this.visible = !this.visible;
      
      return;
}

this.viewContainer.clear();
this.visible = !this.visible;
```

Я бы еще вынес `this.visible = !this.visible;` перед `if` блоком:
```ts
this.visible = !this.visible;

if (template && !this.visible) {
      this.viewContainer.createEmbeddedView(template);
      
      return;
}

this.viewContainer.clear();
```

2023-01-12 10:18 UTC, IlyaPershin commented on src/app/shared/popup/popup.component.ts
> +    } else {
с визиблом согласен, перенесу, но с ранним ретурном в этом конкретном случае не согласен

2023-01-12 10:18 UTC, IlyaPershin commented
Внес еще доработки

2023-01-15 13:52 UTC, Letto228 approved these changes
Отлично, последние изменения просмотрел, все гуд! По поводу if/else напишу в дискорде, вынесем обсуждение туда

2023-01-15 13:53 UTC, closed without merging