feat: реализация шаблона для диалогового окна
Letto228/Angular-learnjs-121222 pull request #69
Opened 2023-01-03 10:01 UTC by DmChupin

2023-01-09 07:45 UTC, DmChupin commented
@Letto228 Егор, привет! 
А можешь подсказать - как нам сделать проверку на то, что мы передали в popup пустой template и не отображать его в таком случае?
`
<app-popup-host [popupTemplate]="template"></app-popup-host>

<ng-template #template>
</ng-template>
`
Интересует как это можно обработать в PopupHostComponent в set popupTemplate

2023-01-10 07:07 UTC, Letto228 commented
Привет!
Постарался найти такую возможность, но успехом поиски мои не увенчались: у `TemplateRef` есть свойство `elementRef.nativeElement`, но оно привязанно к `comment`, из которого мало полезной информации можно выудить; сам по себе, шаблон это набор инструкций по формированию DOM узла и явного доступа к этим инструкциям у нас нет, по этому и узнать, какой view будет построен при вызове запуске данных инструкций у нас не получится.

2023-01-10 07:10 UTC, Letto228 requested changes
Добавил еще пару минорных комментариев хорошим практикам, посмотри, пожалуйста

2023-01-10 07:10 UTC, Letto228 commented on src/app/shared/popup/popup-host/popup-host/popup-host.component.ts
> +	@Input() set popupTemplate(template: TemplateRef<unknown>) {
Давай добавим в типизацию `undefined`

2023-01-10 07:10 UTC, Letto228 commented on src/app/shared/popup/popup-host/popup-host/popup-host.component.ts
> +		this.viewContainer?.clear();
Контейнер статичен и всегда существует, по этому нет необходимости тут использовать optional chaining

2023-01-15 14:22 UTC, Letto228 requested changes
Отлично! Оставил комментарий по скрытию popup-host, посмотри, пожалуйста

2023-01-15 14:22 UTC, Letto228 commented on src/app/shared/popup/popup-host/popup-host/popup-host.component.less
> +:empty {
Здорово, что применил данный селектор!
Но есть один нюанс, хост компонента не пустой, у него есть дочерняя нода -  `comment`, которая порождается `ng-container`, в следствии чего селектор не будет применен

Попробуй для скрытия контейнера посмотреть в сторону `@HostBinding('style.display') private hostDisplay`. При наличии вставленных элементов в контенер(`this.viewContainer.length !== 0 `) должен применяться стиль `this.hostDisplay = 'block'`, в иных ситуациях(в тех, когда кол-во элементов в контейнере равно нулю) должен применяться стиль `this.hostDisplay = 'none'`.
P.S. можно посмотреть в сторону использования гетера для `@HostBinding('style.display')`

2023-01-25 17:41 UTC, DmChupin commented
Привет. Тут тоже подправил. С геттером пришлось освежить память, так корректно реализовано?

2023-01-26 04:27 UTC, Letto228 approved these changes
Да, все верно
Красота) - апрув

2023-01-26 04:27 UTC, closed without merging