feat: add product card
Letto228/Angular-learnjs-121222 pull request #71
Opened 2023-01-05 14:56 UTC by AK20001701

ДЗ lecture-2

2023-01-08 21:37 UTC, Letto228 requested changes
Привет!
Есть один комментарий по `innerHTML`, посмотри, пожалуйста. В остальном все гуд!

2023-01-08 21:37 UTC, Letto228 commented on src/app/products-list/product-card/product-card/product-card.component.html
> +		<h1 class="card-header" [innerHTML]="product.name"></h1>
Почему в некоторых кейсах использовал `innerHTML`?

2023-01-08 21:37 UTC, Letto228 commented on src/app/products-list/product-card/product-card/product-card.component.html
> +			(click)="nextImg($event)"
Немного странный пользовательский опыт - по клику на изображение показывать следующее изображение, но в целом - ок

2023-01-08 21:39 UTC, AK20001701 commented on src/app/products-list/product-card/product-card/product-card.component.html
> +		<h1 class="card-header" [innerHTML]="product.name"></h1>
У меня как раз возник вопрос, лучше использовать байдинг в для innerHTML, или в случае передачи просто текстового значения лучше использование {{}}?

2023-01-11 04:59 UTC, Letto228 commented on src/app/products-list/product-card/product-card/product-card.component.html
> +		<h1 class="card-header" [innerHTML]="product.name"></h1>
Если ты хочешь отобразить текст на странице, то есть вставить текстовую ноду, то стоит использовать интерполяцию:
```html
<h1 class="card-header">{{product.name}}</h1>
```

2023-01-14 14:19 UTC, AK20001701 commented on src/app/products-list/product-card/product-card/product-card.component.html
> +		<h1 class="card-header" [innerHTML]="product.name"></h1>
Заменил binding на интерполяцию

2023-01-15 14:24 UTC, Letto228 approved these changes
Отлично, все гуд!
Апрув

2023-01-15 14:24 UTC, closed without merging