feat: lecture 2
Letto228/Angular-learnjs-121222 pull request #72
Opened 2023-01-05 15:04 UTC by AntonT85

2023-01-08 21:46 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста.

Есть еще общий кейс по статичному коду в шаблоне компонента карточки: его быть не должно(статичного кода для конкретного продукта), т.к. карточка должна быть максимальо гибкой, чтобы в ней можно было показать любой продукт, не меняя шаблон. У тебя в шаблоне 2 места, где используется статичное писание товара: `<mat-card-content>` и `<mat-card-subtitle>`.
Но, спишем это на не полноту модели товара для карточки) По этому, можно не править, решил просто подсветить данный момент

2023-01-08 21:46 UTC, Letto228 commented on src/app/products-list/product-card/product-card.html
> +	<img mat-card-image src="{{card.images[0].url}}" />
Почему решил использовать интерполяцию, а не `binding`?

2023-01-08 21:46 UTC, Letto228 commented on src/app/products-list/product-card/product-card.html
> +			>1280x800, IPS, 4х1.3 ГГц, 2 Гб, BT, GPS, 4500 мАч, Android
`prettier` не всегда умеет хорошо форматировать html. Это одно из таких мест, давай его подправим - перенесем текст на следующую строку сами

2023-01-09 10:45 UTC, AntonT85 commented
> Привет! Оставил пару комментариев, посмотри, пожалуйста.
> 
> Есть еще общий кейс по статичному коду в шаблоне компонента карточки: его быть не должно(статичного кода для конкретного продукта), т.к. карточка должна быть максимальо гибкой, чтобы в ней можно было показать любой продукт, не меняя шаблон. У тебя в шаблоне 2 места, где используется статичное писание товара: `<mat-card-content>` и `<mat-card-subtitle>`. Но, спишем это на не полноту модели товара для карточки) По этому, можно не править, решил просто подсветить данный момент

Да, странно, что я так сделал) Конечно нужно было через параметр делать

2023-01-09 10:50 UTC, AntonT85 commented on src/app/products-list/product-card/product-card.html
> +	<img mat-card-image src="{{card.images[0].url}}" />
Копипастом с имени продукта, до конца пока не отложились эти конструкции

2023-01-09 10:51 UTC, AntonT85 commented on src/app/products-list/product-card/product-card.html
> +	<img mat-card-image src="{{card.images[0].url}}" />
Напиши плиз, почему в этом случае это не ок

2023-01-09 10:58 UTC, AntonT85 commented
Запушил правки

2023-01-11 05:12 UTC, Letto228 commented on src/app/products-list/product-card/product-card.html
> +	<img mat-card-image src="{{card.images[0].url}}" />
Отличие в технической части:
- binding прикрепляет реальное значение: передал объект, значит в свойство передастся объект
- интерполяция превращает значение в строку: передал объект, значит передастся `Object.toString()`

Из этих особенностей складывается идеологический принцип, который необходим для организации чистого кода: для отображения контента на странице, т.е. вставки текстовой ноды, используем интерполяцию; для передачи значенией в свойства элемента или инпут свойства компонента используется binding(чтобы сохранить оригинальность данных)

2023-01-11 05:16 UTC, Letto228 commented on src/app/products-list/product-card/product-card.html
> +	<img mat-card-image src="{{card.images[0].url}}" />
Подытожив: если свойство ожидает строковый тип данных, то можно использовать и binding и интерполяцию, оба способа будут работать одинаково хорошо. НО, по идеологическим соображениям(которые нужны для чистоты кода), для привязки свойства элемента или инпут свойства компонента - используем binding, чтобы передать оригинальные привязанные данные

2023-01-11 05:19 UTC, Letto228 commented on src/app/products-list/product-card/product-card.html
> +	<img mat-card-image src="{{card.images[0].url}}" />
> Напиши плиз, почему в этом случае это не ок

И отвечая на вопрос: не ок, потому что код загрязняется и становится не консистентным, т.к. для передачи данных где то будет использоваться интерполяция, где то binding, и в итоге получится неразбериха

2023-01-12 04:58 UTC, Letto228 approved these changes
Отлично! - апруваю

2023-01-12 04:58 UTC, closed without merging