Lecture-3
Letto228/Angular-learnjs-121222 pull request #73
Opened 2023-01-06 00:14 UTC by AK20001701

2023-01-06 00:15 UTC, AK20001701 commented on src/app/modules/products-list/product-card/product-card.component.html
> +			product?.name ?? 'Продукт не существует'
Не совсем понял что имелось ввиду под пунктом
"2. Обработать кейс, когда с инпут свойстве хранится undefined"
Достаточно ли того, что сделал я, или что имелось ввиду?

2023-01-08 21:56 UTC, Letto228 requested changes
Привет!
Оставил один комментарий по поводу тернарников, в остальном все огонь 🔥

2023-01-08 21:56 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +			[disabled]="product === undefined ? true : false"
Тавтология получилась, тернарник кажется тут излишним и можно оставить только `product === undefined`).

2023-01-08 21:56 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +			product?.name ?? 'Продукт не существует'
Да, в итоге ты все верно сделал, этого более чем достаточно 👍

2023-01-08 22:00 UTC, AK20001701 commented on src/app/modules/products-list/product-card/product-card.component.html
> +			[disabled]="product === undefined ? true : false"
Да, смешной момент получился, не заметил как-то…
Этот момент надо исправить и выложить с исправлением?

2023-01-11 05:20 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.html
> +			[disabled]="product === undefined ? true : false"
Да, давай исправим и с чистой душой поставлю апрув на МР

2023-01-14 14:24 UTC, AK20001701 commented on src/app/modules/products-list/product-card/product-card.component.html
> +			[disabled]="product === undefined ? true : false"
Исправил

2023-01-15 14:26 UTC, Letto228 approved these changes
Гуд! - апрув

2023-01-15 14:26 UTC, closed without merging