feat: dz-5. infinite-scroll.directive
Letto228/Angular-learnjs-121222 pull request #74
Opened 2023-01-06 07:29 UTC by sergey-gonchar

2023-01-10 05:42 UTC, Letto228 requested changes
Привет!
Есть пару вопросов по логике, посмотри, пожалуйста

2023-01-10 05:42 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const directionDown = element.scrollHeight - element.scrollTop - element.offsetHeight <= this.borderOffset;
Кажется, `offsetHeight` не очень подходит для нашей задачи, давай посмотри в сторону `clientHeight` свойства https://learn.javascript.ru/size-and-scroll#clientwidth-height

2023-01-10 05:42 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const directionUp = element.scrollTop <= this.borderOffset;
Нейминг кажется не совсем верный, `element.scrollTop <= this.borderOffset` не говорит же о направлении скролла, а говорит о приближении/пересечении к верхней границе. Вполне вероятен кейс, когда с самого верха будем скроллить вниз, но `scrollTop` по прежнему будет меньше `borderOffset`, получается что `directionUp === true` при скролле вниз, и это немного вводит в диссонанс.

2023-01-10 05:42 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		if (directionUp && updateOnScrollUp) {
Есть хорошая практика по использованию if/else - не использовать else)
Я в практике использую подход с ранним ретерном, и он, как мне кажется, чище чем конструкции с `else`, а так же более гибкий.
```ts
if (directionUp && updateOnScrollUp) {
		this.offsetIntersected.emit(ScrollDirection.up);
		this.previousDirection = ScrollDirection.up;

		return;
}

if (directionDown && updateOnScrollDown) {
		this.offsetIntersected.emit(ScrollDirection.down);
		this.previousDirection = ScrollDirection.down;
		this.previousScrollHeight = element.scrollHeight;

		return;
}
```

Но данная тема холиварная, по этому комментарий носит исключительно рекомендационный характер

2023-01-10 05:42 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +			this.previousScrollHeight = element.scrollHeight;
Почему `previousScrollHeight` изменяется только при скролле вниз?

2023-01-10 05:42 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const updateOnScrollUp = this.previousDirection === ScrollDirection.down;
Кажется что подгрузки при скролле вверх почти не предусмотрено(подгрузка сверху происходит только при изменении direction, т.е. если я захочу 2 раза загрузить данные сверху, то придется 1 раз загрузить данные снизу, чтобы сменить direction)

2023-01-10 05:42 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +export enum ScrollDirection {
Давай вынесем в отдельный файл enum - `scroll-direction.enum.ts`, чтобы не загрязнять файл директивы

2023-01-10 13:55 UTC, sergey-gonchar commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +export enum ScrollDirection {
вынес

2023-01-10 13:56 UTC, sergey-gonchar commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const updateOnScrollUp = this.previousDirection === ScrollDirection.down;
поправил

2023-01-10 13:56 UTC, sergey-gonchar commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +			this.previousScrollHeight = element.scrollHeight;
хм, действительно странно, недосмотрел. Исправил

2023-01-10 13:57 UTC, sergey-gonchar commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		if (directionUp && updateOnScrollUp) {
принял как истину, посмотрим что выйдет

2023-01-10 13:57 UTC, sergey-gonchar commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const directionUp = element.scrollTop <= this.borderOffset;
нейминг исправил

2023-01-10 13:57 UTC, sergey-gonchar commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const directionDown = element.scrollHeight - element.scrollTop - element.offsetHeight <= this.borderOffset;
угу, clientHeight не учитывает маржины и бордеры, здесь действительно лучше

2023-01-11 05:34 UTC, Letto228 approved these changes
Огонь 🔥
Прочиталось все легко, есть комментарий по логике(дублирующая проверка) и микрокоммент по читаемости, посмотри, пожалуйста.
Комментарии, которые оставил, не критичны, ДЗ в целом выполнено, по этому смело ставлю апрув и закрываю МР

2023-01-11 05:34 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +			element.scrollHeight - element.scrollTop - element.clientHeight <= this.borderOffset && previousTopGreater;
`element.scrollHeight - element.scrollTop - element.clientHeight` вот это бы вынести в константу и было бы вообще супер

2023-01-11 05:34 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const intersectedTopBorder = element.scrollTop <= this.borderOffset && previousTopLower;
У тебя проверка `&& previousTopLower` and `&& previousTopGreater` встречается и в `intersectedTopBorder` and `intersectedBottomBorder`, а так же в `if` блоках, т.е. одна и та же проверка выполняется 2 раза.

Предлагаю убрать `&& previousTopLower` and `&& previousTopGreater` из `intersectedTopBorder` and `intersectedBottomBorder`, так и значение в константах будут лучше неймингу соответствовать* и двойную проверку уберем


\* \- в них будет хранится значение только о пересечении верхней или нижней границы, не беря в расчет `previousTopLower` and `previousTopGreater`, т.к. оно на пересечение границ не влияет

2023-01-11 05:34 UTC, closed without merging