Lecture 3 dz (input-output decorators)
Letto228/Angular-learnjs-121222 pull request #75
Opened 2023-01-06 16:20 UTC by Dimash77777

2023-01-09 04:33 UTC, Letto228 requested changes
Привет!
Все супер, оставил пару комментариев, посмотри, пожалуйста

2023-01-09 04:33 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() buyClick = new EventEmitter<Event>();
Давай подумаем над более полезными данными в `$event` аутпута, вряд ли компоненту-родителю будет полезно событие клика.
Думаю, `_id` продукта в `$event` для компонента-родителя будет намного полезнее

2023-01-09 04:33 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		return Boolean(this.product && this.product?.rating >= starIndex);
optional chaining тут кажется излишним, получается масло масленное т.к. до этого проверили наличие продутка(`this.product &&`)

2023-01-10 18:59 UTC, Dimash77777 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		return Boolean(this.product && this.product?.rating >= starIndex);
Спасибо, все подправил.

2023-01-11 05:35 UTC, Letto228 approved these changes
Супер! Ставлю апрув

2023-01-11 05:36 UTC, closed without merging