feat: infinite scroll directive (lecture 5)
Letto228/Angular-learnjs-121222 pull request #77
Opened 2023-01-07 08:42 UTC by mrfrac

2023-01-09 04:56 UTC, Letto228 requested changes
Привет!
Все супер, есть пару мелких комментариев, посмотри, пожалуйста

2023-01-09 04:56 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +	@Output() topReached = new EventEmitter<void>();
Давай попробуем сделать универсальный аутпут с эвентом?
`topReached` и `bottomReached` говорят о том, что при скролле был достигнут верх или низ, но это не совсем правда, потому что у нас стоит `offset`, который отстраняет реальную верхнюю и нижнюю границу. По этмоу предлагаю назвать `output` по его прямому назначению - загрузка данных. Т.е. в моем понимании аутпут свойства должны были бы называться `loadBefore` и `loadAfter`.
Но тут возникает другой вопрос, раз два аутпута говорят об одном и том же, не лучше ли их сделать едиными: вместо `loadBefore` и `loadAfter` сделать `load` аутпут и в его эвенте прокидывать направление загрузки `before`/`after`. В целом и к `topReached` и `bottomReached` можно применить данный кейс: аутпут говорит, что граница достигнута, а `$event` показывает какая из границ была достигнута

2023-01-09 04:56 UTC, Letto228 commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const isBottomReached = target.scrollHeight - target.scrollTop - target.offsetHeight <= this.offset;
Думаю `offsetHeight` тут использовать не совсем корректно, стоит посмотреть в сторону `clientHeight` https://learn.javascript.ru/metrics#clientwidth-height

2023-01-09 10:34 UTC, mrfrac commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +	@Output() topReached = new EventEmitter<void>();
Доработал :)

2023-01-09 10:35 UTC, mrfrac commented on src/app/shared/infinite-scroll/infinite-scroll.directive.ts
> +		const isBottomReached = target.scrollHeight - target.scrollTop - target.offsetHeight <= this.offset;
✔️

2023-01-11 06:03 UTC, Letto228 approved these changes
Огонь 🔥 
Есть один комментарий по `debounce`, посмотри, пожалуйста.
Задание по скроллу выполнено, в дебаунсе тоже нет ничего криминального, по этому - апруваю и закрываю МР

2023-01-11 06:03 UTC, closed without merging