feat: lecture 5 dz
Letto228/Angular-learnjs-121222 pull request #78
Opened 2023-01-07 12:35 UTC by nigavshin

2023-01-09 06:01 UTC, sergey-gonchar commented
Очень похоже на мою реализацию)

2023-01-09 06:08 UTC, nigavshin commented
Ага, я только сомневаюсь по поводу инпутов и аутпутов

2023-01-09 10:36 UTC, mrfrac commented
> Очень похоже на мою реализацию)

я тоже у тебя идею подсмотрел по поводу арифметики :)

2023-01-10 05:55 UTC, Letto228 requested changes
Привет!
Раз реализация очень похожа, то и смежные комментарии имеются) Оставил еще пару комментариев по неймингу и чистоте кода, посмотри, пожалуйста

2023-01-10 05:55 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +		const scrollUp = scrollTop <= this.offset;
Нейминг кажется не совсем верный, `scrollTop <= this.offset ` не говорит же о направлении скролла, а говорит о приближении/пересечении к верхней границе. Вполне вероятен кейс, когда с самого верха будем скроллить вниз, но `scrollTop` по прежнему будет меньше `offset`, получается что `scrollUp === true` при скролле вниз, и это немного вводит в диссонанс.

2023-01-10 05:55 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +			this.previousScrollHeight = scrollHeight;
Почему `previousScrollHeight` изменяется только при скролле вниз?

2023-01-10 05:55 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +		const updateOnScrollUp = this.previousDirection === LoadDirection.down;
Кажется что подгрузки при скролле вверх почти не предусмотрено(подгрузка сверху происходит только при изменении direction, т.е. если я захочу 2 раза загрузить данные сверху, то придется 1 раз загрузить данные снизу, чтобы сменить direction)

2023-01-10 05:55 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +export enum LoadDirection {
Давай вынесем в отдельный файл enum - `scroll-direction.enum.ts`, чтобы не загрязнять файл директивы

2023-01-10 05:55 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +		// console.log(`scrollHeight = ${scrollHeight}`, `clientHeight = ${clientHeight}`);
Комментарии предлагаю стереть)

2023-01-10 05:55 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +	@Output() bottomScroll = new EventEmitter<LoadDirection>();
Думаю, два `Output` тут излишни: в `Output` ты передаешь `LoadDirection`, то есть направление загрузки данных, в таком случае необходим 1 `Output`, в котором будет передаваться направление загрузки:
load + `LoadDirection.up` === topScroll
load + `LoadDirection. down ` === bottomScroll

2023-01-10 05:55 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +	@Output() bottomScroll = new EventEmitter<LoadDirection>();
И, я бы поменял нейминг, т.к. `topScroll` говорит не совсем о скролле верх, с `bottomScroll` ситуация аналогична. Такие нейминги подходили бы, если просто проверялось направление скролла, без проверки пересечения верхней/нижней границы(offset)

2023-01-10 17:10 UTC, nigavshin commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +		const scrollUp = scrollTop <= this.offset;
исправил

2023-01-10 17:25 UTC, nigavshin commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +		// console.log(`scrollHeight = ${scrollHeight}`, `clientHeight = ${clientHeight}`);
исправил

2023-01-10 17:43 UTC, nigavshin commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +	@Output() bottomScroll = new EventEmitter<LoadDirection>();
исправил

2023-01-10 18:06 UTC, nigavshin commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +		const updateOnScrollUp = this.previousDirection === LoadDirection.down;
исправил

2023-01-11 06:28 UTC, Letto228 requested changes
Остался вопрос к логике отправки события загрузки, оставил комментарий, посмотри, пожалуйста

2023-01-11 06:28 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +	@Output() LoadDirection = new EventEmitter<LoadDirection>();
`@Output() LoadDirection` -> `@Output() loadDirection`, т.к. это свойство компонента

2023-01-11 06:28 UTC, Letto228 commented on src/app/shared/infinity-scroll/infinity-scroll.directive.ts
> +		const updateOnScrollUp = this.previousDirection === LoadDirection.down;
Кажется, осталась такая же логика `updateOnScrollUp` будет true только в том случае, если произойдет сначала загрузка данных снизу

Я бы предложил в целом пересмотреть подход: смотреть, что скролл происходит вверх и есть пересечение с `offset`, т.е. `isBorderFarAway` and `isBorderFarAway` это пересечение с верхней и нижней границей отступа соответсвенно, остается только определить, в какую сторону происходит скролл - вверх или вниз. В итоге, если скролл происходит вверх и есть пересечение с верхней границей отступа - загружаем данные с `direction === LoadDirection.up`, если скролл происходит вниз и есть пересечение с нижней границей отступа - загружаем данные с `direction === LoadDirection.down`

2023-01-19 05:03 UTC, Letto228 commented
Отлично - апрув

2023-01-19 05:03 UTC, closed without merging