feat: add card component
Letto228/Angular-learnjs-121222 pull request #79
Opened 2023-01-07 21:25 UTC by IvanBiushkin

2023-01-09 05:10 UTC, Letto228 requested changes
Привет!
Все гуд, надо доработать пару нюансов, отписал и в комментариях, посмотри, пожалуйста

2023-01-09 05:10 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.less
> +	background-image: url('https://c.dns-shop.ru/thumb/st1/fit/0/0/dff090e667cd39dd397678905df52de5/6c3e7aab802deb19513c7cf55dd7c527efb9127d8aba2ed90f3d224577137fe2.jpg');
Мы делаем динамический компонент карточки и статичному коду в нем не место)
Давай будем прикреплять `background-image` динамически оснывываясь на данных из `card`

2023-01-09 05:10 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +		if (this.imageIndex + 1 == this.card.images.length - 1) {
Сложное выражение в условии `if` - прямой путь к сложночитаемому коду. Давай все выражения из условии `if` вынесем в константы с говорящим названием

2023-01-09 05:10 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.ts
> +		if (this.imageIndex + 1 == this.card.images.length - 1) {
`this.card.images.length - 1` - можно тоже вынести в геттер, и назвать его а ля `lastImageIndex`, так код должен читаться еще проще

2023-01-09 05:10 UTC, Letto228 commented on src/app/products-list/product-card/product-card.component.html
> +		[src]="card.images.length > 0 ? card.images[imageIndex].url : ''"
В Angular комъюнити есть 2 лагеря: те кто любит писать логику в шаблоне и пропагандирует это, и те, кто против загрязнения шаблона логикой. Я отношусь ко вторым)
Собственно предлагаю тебе этот тернарник вынести в метод компонента, чтобы не грузить шаблон логикой. Опять же, все это для улучшения читаемость шаблона

2023-01-11 19:02 UTC, IvanBiushkin commented on src/app/products-list/product-card/product-card.component.less
> +	background-image: url('https://c.dns-shop.ru/thumb/st1/fit/0/0/dff090e667cd39dd397678905df52de5/6c3e7aab802deb19513c7cf55dd7c527efb9127d8aba2ed90f3d224577137fe2.jpg');
Спасибо за ревью, вроде все поправил)

2023-01-12 05:00 UTC, Letto228 approved these changes
Замечательно! - апрув

2023-01-12 05:00 UTC, closed without merging