feat: lecture-3
Letto228/Angular-learnjs-121222 pull request #81
Opened 2023-01-08 16:44 UTC by AntonT85

2023-01-09 06:21 UTC, Letto228 requested changes
Привет!
Все круто, есть один не большой нюанс, описал его в комментарии, посмотри, пожалуйста

2023-01-09 06:21 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Output() productBuyClick = new EventEmitter<Event>();
Давай подумаем над более полезными данными в Output? Думаю событие клика для компонента-родителя не очень информативно, `_id` покупаемого продукта, кажется, было бы намного полезнее

2023-01-09 11:15 UTC, AntonT85 commented
Спасибо, поправил

2023-01-11 05:52 UTC, Letto228 approved these changes
Все гуд, апрув

2023-01-11 05:52 UTC, closed without merging