feat: lecture 4
Letto228/Angular-learnjs-121222 pull request #82
Opened 2023-01-09 16:39 UTC by AntonT85

2023-01-11 07:05 UTC, Letto228 requested changes
Привет!
Супер! Со вставкой темплейта вопросов нет. Но есть вопрос по расположению хоста: предполагается, что хост будет располагаться над всем контентом на странице и в нем будет располагаться `popup`, т.е. нужно добавить стили для расположения `popup-host` над всем приложением. Но тогда возникает проблема, что весь контент будет перекрыт, она решается двумя способами:
1. HostBinding - можно при помощи стилей скрыть `popup-host` или сделать его прозрачным. Похожий подход я использовал в своем решении
2. Добавить в `popup-host` `div` обертку и расположить `<ng-container #viewContainer>` внутри данной обертки. Далее принцип все тот же, что и в первом пункте: при помощи binding и стилей `div` обертки - скрываем ее или делаем прозрачной

2023-01-20 16:48 UTC, AntonT85 commented
Поправил

2023-01-22 19:53 UTC, Letto228 commented
Все супер - апрув!

2023-01-22 19:53 UTC, Letto228 approved these changes

2023-01-22 19:54 UTC, closed without merging