feat: dz6. paginator.directive
Letto228/Angular-learnjs-121222 pull request #85
Opened 2023-01-10 19:34 UTC by sergey-gonchar

2023-01-13 08:54 UTC, Letto228 requested changes
Привет!
Все супер, но нужно чутка доработать, оставил комментарии, посмотри, пожалуйста

2023-01-13 08:54 UTC, Letto228 commented on src/app/shared/paginator/paginator.directive.ts
> +			this.updateView();
Сейчас отправка значения в `currentPage$` сабжект и отработка его подписки происходит синхронно: запушил значение === синхронное запустил `subscribe`. И, обрати, пожалуйста, внимание на порядок действий, ты сначала обновляешь контекст и только потом обновляешь свойство `pages`, на основе которого собирается контекст.
В итоге - у нас имеется баг, при смене элементов в инпут свойстве - отображается паганация со старыми данными

2023-01-13 08:55 UTC, Letto228 commented on src/app/shared/paginator/paginator.directive.ts
> +			this.updateView();
Чтобы визуализировать баг, поставь такой `ngOnInit` в компонент `ProductsListComponent`:
```ts
	ngOnInit() {
		setTimeout(() => {
			this.products = productsMock;
			this.changeDetectorRef.detectChanges();
		}, 3000);

		setTimeout(() => {
			this.products = [...productsMock].reverse().map(item => ({ ...item, rating: 3 }));
			this.changeDetectorRef.markForCheck();
		}, 6000);
	}
```

2023-01-13 09:44 UTC, sergey-gonchar commented on src/app/shared/paginator/paginator.directive.ts
> +			this.updateView();
готово

2023-01-13 09:44 UTC, sergey-gonchar commented on src/app/modules/products-list/products-list.component.html
> +		*ngFor="let _ of [].constructor(size); let index = index"
извлек метод для подготовки страниц

2023-01-15 14:34 UTC, Letto228 approved these changes
Огонь 🔥  - апрув

2023-01-15 14:34 UTC, closed without merging