Реализована директива скроллера по продуктам
Letto228/Angular-learnjs-121222 pull request #86
Opened 2023-01-11 11:35 UTC by IlyaPershin

2023-01-12 05:34 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста. Решение очень хорошее, но нужно чуть подкрутить

2023-01-12 05:34 UTC, Letto228 commented on src/app/shared/scroller/scroller.directive.ts
> +    if (scrollDirection === ScrollDirection.Up && isFirstTop) return this.loadData.emit(ScrollDirection.Up);
Поинт к if блоку - я бы рекомендовал всегда его дописывать до конца, т.е. добавлять фигурные скобки, делается это исключительно для чистоты кода и улучшения читаемости

2023-01-12 05:34 UTC, Letto228 commented on src/app/shared/scroller/scroller.directive.ts
> +    const scrollDirection: ScrollDirection = target.scrollTop < this.topOffset ? ScrollDirection.Up : ScrollDirection.Down;
Немного смущает, что булевое значение, говорящее о направлении скролла(`target.scrollTop < this.topOffset`), переводим в значение `ScrollDirection`, а ниже, в `if` блоках, снова приводим к булевому значению и больше `scrollDirection` нигде не используем.
В целом, идея хранения направления - огонь, т.е. я бы оставил `scrollDirection: ScrollDirection`, но повысил бы его полезность: не проставлял в `loadData.emit` фиксированное значение из Enum, а передавал бы `scrollDirection`. Т.е. логика такая: высчитали направление(`scrollDirection`) -> проверили, что нужно эмитить событие загрузки(логика `if` блоков) -> отправили событие загрузки с вычисленным направлением(`this.loadData.emit(scrollDirection)`)

```ts
const needLoadBefore = scrollDirection === ScrollDirection.Up && isFirstTop;
const needLoadAfter = scrollDirection === ScrollDirection.Down && isFirstBottom;

if (needLoadBefore || needLoadAfter) {
    this.loadData.emit(scrollDirection);
}
```

2023-01-12 12:30 UTC, IlyaPershin commented on src/app/shared/scroller/scroller.directive.ts
> +    if (scrollDirection === ScrollDirection.Up && isFirstTop) return this.loadData.emit(ScrollDirection.Up);
ок

2023-01-12 12:30 UTC, IlyaPershin commented on src/app/shared/scroller/scroller.directive.ts
> +    const scrollDirection: ScrollDirection = target.scrollTop < this.topOffset ? ScrollDirection.Up : ScrollDirection.Down;
Согласен, так лучше

2023-01-12 12:30 UTC, IlyaPershin commented
Внес изменения

2023-01-15 14:35 UTC, Letto228 approved these changes
Да, со всем согласен; Огонь 🔥  - апрув

2023-01-15 14:35 UTC, closed without merging