feat: popup-host template
Letto228/Angular-learnjs-121222 pull request #87
Opened 2023-01-11 20:48 UTC by Dimash77777

2023-01-13 06:59 UTC, Letto228 requested changes
Привет!
Огонь, по вставке темплейта вопросов нет, все как надо. Но есть замечания к стилям хоста попапа: предполагается, что хост будет располагаться над всем контентом на странице и в нем будет располагаться `popup`, т.е. нужно добавить стили для расположения `popup-host` поверх всего приложения. Но тогда возникает проблема, что весь контент будет перекрыт, она решается двумя способами:
1. HostBinding - можно при помощи стилей скрыть `popup-host` или сделать его прозрачным. Похожий подход я использовал в своем решении
2. Добавить в `popup-host` `div` обертку и расположить `<ng-container #viewContainer>` внутри данной обертки. Далее, принцип все тот же, что и в первом пункте: `div` обертку располагаем над всем контентом на странице, и при помощи binding и стилей `div` обертки - скрываем ее или делаем прозрачной.

2023-01-13 06:59 UTC, Letto228 commented on src/app/shared/popup/popup-host/popup-host.component.ts
> +	@Input() set popupTemplate(template: TemplateRef<unknown>) {
Давай укажем в типизации, что в `template` может придти `undefined`

2023-01-15 17:15 UTC, Dimash77777 reviewed
Егор, я к сожалению не силен в css-стилях, поэтому за образец взял стили из твоего решения ) И еще вопрос - в решении данного дз необходимо делать вызов popup? Просто сейчас он не показывается.

2023-01-17 06:03 UTC, Letto228 commented
Нет, никакого вызова не предусматривалось, достаточно просто в инпут передать TempalteRef. Вечером постараюсь склонировать твой репозиторий, посмотреть и отписаться, что пошло не так и почему попап не отображается

2023-01-17 18:08 UTC, Letto228 commented
<img width="1792" alt="Снимок экрана 2023-01-17 в 21 06 41" src="https://user-images.githubusercontent.com/54375830/212977441-c4fd0e24-9db5-449b-878c-0c7616681844.png">

Посмотрел, все дело в `z-index` свойстве `popup-host` компонента, попробуйй сделать его побольше и все будет

2023-01-17 19:34 UTC, Dimash77777 commented
Большое спасибо, Егор, все получилось!

2023-01-19 05:06 UTC, Letto228 approved these changes
Супер! Апрув

2023-01-19 05:06 UTC, closed without merging