feat: lecture-3 features
Letto228/Angular-learnjs-121222 pull request #88
Opened 2023-01-11 21:38 UTC by IvanBiushkin

2023-01-12 05:05 UTC, Letto228 requested changes
Привет!
Оставил пару комментариев, посмотри, пожалуйста

2023-01-12 05:05 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +		if (this.cardInfo) return this.cardInfo;
Я рекомендую дописывать if блоки до конца, так они читаются проще и код получается чище
В данном кейсе лучше всего подошел бы тернарный оператор, давай его и используем

2023-01-12 05:05 UTC, Letto228 commented on src/app/modules/products-list/product-card/product-card.component.ts
> +	@Input() cardInfo: any;
У приходящих значений есть интерфейс - `IProduct`, давай его использовать. К тому же не стоит забывать, что кроме `IProduct` может придти и `undefined`

2023-01-22 12:51 UTC, IvanBiushkin commented
Привет)
Спасибо за ревью, сделал исправления по твоим комментариям

2023-01-22 20:01 UTC, Letto228 approved these changes
Гуд! - апрув

2023-01-22 20:01 UTC, closed without merging