feat: добавлена директива для отправки события о необходимости подгрузки данных
Letto228/Angular-learnjs-121222 pull request #91
Opened 2023-01-14 20:22 UTC by DmChupin

2023-01-15 17:42 UTC, Letto228 requested changes
Привет!
Все по логике все супер, оставил комментарии по чистоте кода, посмотри, пожалуйста

2023-01-15 17:42 UTC, Letto228 commented on src/app/shared/insert-scroll/insert-scroll.directive.ts
> +	appInsertScroll = new EventEmitter<string>();
Предлагаю создать `enum`, в котором опишем возможные направление загрузки. При помощи данного `enum` можно будет типизировать `Output`, т.к. сейчас, компонент-родитель знает только то, что ему может придти любая абстрактная строка. Плюс от более строгого типизирования `Output` - не придется искать по коду, какие значения в нем отправляются, чтобы понять как их обработать.

Заранее предложу -  `enum` лучше объявить и заэкспортировать в другом файле(`enum-name.ts`), чтобы не загрязнять файл директивы

2023-01-15 17:42 UTC, Letto228 commented on src/app/shared/insert-scroll/insert-scroll.directive.ts
> +	readonly offset = 100;
Думаю, эти два свойства должны быть приватными

2023-01-15 17:42 UTC, Letto228 commented on src/app/shared/insert-scroll/insert-scroll.directive.ts
> +		if (scrollTop < this.offset) return true;
Аналогично комментарию выше

2023-01-15 17:42 UTC, Letto228 commented on src/app/shared/insert-scroll/insert-scroll.directive.ts
> +		if (border < this.offset) return true;
Кажется, что if блок тут и вовсе не нужен, достаточно просто вернуть результат сравнения `scrollTop < this.offset`

2023-01-15 17:42 UTC, Letto228 commented on src/app/shared/insert-scroll/insert-scroll.directive.ts
> +		if (scrollTop > lastPoint) {
Чем больше вложенных if блоков, тем сложнее читать код. Некоторые разработчики используют правило - максимальная вложенность if блоков === 1, и я тоже стараюсь придерживаться данного правила) У тебя, к примеру, уровень вложенности === 2.
Что предлагаю: можно перед if блоком создать константу, которая будет говорить о том, нужно ли заходить в if блок, в твоем случаи константа должна включать 2 условия - направление загрузки и пересечение границы отступа
```ts
const needLoadAfterData = scrollTop > lastPoint && this.shouldScrollDown(scrollTop, scrollHeight, clientHeight);

if (needLoadAfterData) {
    return this.appInsertScroll.emit('down');
}
```

2023-01-25 17:26 UTC, DmChupin commented
Привет!
Все подправил.

2023-01-26 04:29 UTC, Letto228 approved these changes
Отлично! 👍
Апрув

2023-01-26 04:30 UTC, closed without merging