feat: add FilterByParamPipe
Letto228/Angular-learnjs-121222 pull request #94
Opened 2023-01-15 14:44 UTC by dkruglova

2023-01-17 06:19 UTC, Letto228 requested changes
Привет!
Все супер 🔥 . Оставил пару косметических правок, чтобы код сделать почище, посмотри, пожалуйста

2023-01-17 06:19 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +		if (value && value.length) {
Я бы предложил перейти на тернарный оператор, думаю, он тут отлично подойдет

2023-01-17 06:19 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +	transform<T>(value: T[], filterValue: any, filterName: string): T[] | null {
А давай попробуем построже стипизировать аргументы? Ты использовала `keyof T` для приведения на 9 строке, предлагаю на этот же тип заменить `string` у `filterName`, таким образом обозначим TS, что именно один из ключей интерфейса может быть значением.  С `filterValue` тоже можно постараться ужесточить типизацию и принимать только те значения, которые возможны в интерфейсе `T` - `T[keyof T]`

2023-01-17 19:20 UTC, dkruglova commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +		if (value && value.length) {
Да, так лучше. Спасибо! Исправила

2023-01-17 19:21 UTC, dkruglova commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +	transform<T>(value: T[], filterValue: any, filterName: string): T[] | null {
Готово :)

2023-01-17 19:22 UTC, dkruglova commented
Привет! Спасибо большое за комментарии и рекомендации! Правки внесла. Посмотри, пожалуйста :)

2023-01-19 05:09 UTC, Letto228 approved these changes
Perfect - approve

2023-01-19 05:09 UTC, closed without merging