feat: dz-7. filter by param
Letto228/Angular-learnjs-121222 pull request #95
Opened 2023-01-16 07:24 UTC by sergey-gonchar

2023-01-17 06:27 UTC, Letto228 requested changes
Привет!
Все круто 👍, есть пару минорных вопросов/предложений, посмотри, пожалуйста

2023-01-17 06:27 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +	transform<T>(value: T[], filterValue: unknown, filterParam: string): T[] {
А давай попробуем построже стипизировать аргументы? Предлагаю тип `string` у `filterName` заменить на возможные ключи интерфейса переданного в `T` - `keyof T`, таким образом обозначим TS, что именно один из ключей интерфейса может быть значением данного аргумента.  С `filterValue` тоже можно постараться ужесточить типизацию и принимать только те значения, которые возможны в интерфейсе `T` - `T[keyof T]`

2023-01-17 06:27 UTC, Letto228 commented on src/app/shared/filter-by-param/wildcard.type.ts
> +export type WithWildcards<T> = T & { [key: string]: unknown };
А для чего данный интерфейс?

2023-01-23 17:39 UTC, sergey-gonchar commented on src/app/shared/filter-by-param/wildcard.type.ts
> +export type WithWildcards<T> = T & { [key: string]: unknown };
Не знал про keyof. Поправил, спасибо!

2023-01-26 04:37 UTC, Letto228 approved these changes
Огонь 🔥 
Апрув

2023-01-26 04:37 UTC, closed without merging