feat: pagination directive (lecture 6)
Letto228/Angular-learnjs-121222 pull request #97
Opened 2023-01-16 15:25 UTC by mrfrac

2023-01-17 06:40 UTC, Letto228 requested changes
Привет!
Все гуд, оставил один комментарий по логике и пару по чистоте кода. Посмотри, пожалуйста

2023-01-17 06:40 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +		if (!appPaginationOf) {
Смущает данная проверка, получается, если не изменился инпут `appPaginationOf`, то контейнер очищается? Например, создалось и вставилось view, потом изменился инпут `appPaginationPerPage` и мы просто удалили вставленное view не вставив после этого новое, как итог - остались без view

2023-01-17 06:40 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +			const pagesTotal = Math.ceil(this.appPaginationOf?.length || 0 / this.appPaginationPerPage);
Давай в отдельный метод, а еще лучше чистую функцию, вынесем сборку `pages`, чуть почище сделаем

2023-01-17 06:40 UTC, Letto228 commented on src/app/shared/pagination/pagination.directive.ts
> +		this.currentPageIndex$.pipe(takeUntil(this.destroy$)).subscribe((pageIndex: number) => {
Давай код вынесем в отдельный метод, чтобы `ngOnInit` просто агрегировал методами, этот поинт в сторону чистоты и читаемости

2023-01-18 16:22 UTC, mrfrac commented on src/app/shared/pagination/pagination.directive.ts
> +		if (!appPaginationOf) {
Исправил :)

2023-01-18 16:22 UTC, mrfrac commented on src/app/shared/pagination/pagination.directive.ts
> +			const pagesTotal = Math.ceil(this.appPaginationOf?.length || 0 / this.appPaginationPerPage);
Готово!

2023-01-18 16:23 UTC, mrfrac commented on src/app/shared/pagination/pagination.directive.ts
> +		this.currentPageIndex$.pipe(takeUntil(this.destroy$)).subscribe((pageIndex: number) => {
Готово!

2023-01-19 05:25 UTC, Letto228 approved these changes
Красота!) - апрув

2023-01-19 05:26 UTC, closed without merging