Реализация пайпа для фильтрации
Letto228/Angular-learnjs-121222 pull request #99
Opened 2023-01-19 17:03 UTC by IlyaPershin

2023-01-22 20:51 UTC, Letto228 requested changes
Привет!
Вопросов к логике фильтра нет - огонь. Оставил пару комментариев по читаемости кода, посмотри пожалуйста. И еще накину коммент - 'filterValue1' не очень хороший нейминг, в целом использовать числа в нейминге это плохая практика. Давай для аргументов с числами в нейминге придумаем другие имена?

2023-01-22 20:51 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +    filterValue2: T[K] | null,
А давай это поле тоже сделаем опциональным? Ведь не всегда нужно его передавать в пайп. А еще я бы поменял его с 'filterOperation' местами, ведь мы можем выбрать оператор фильтрации, который не требует доп аргумент, и не бывает такого кейса, что мы передали бы второй аргумент, но не поменяли бы оператор фильтрации.

2023-01-22 20:51 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +    filterValue2: T[K] | null,
А давай это поле тоже сделаем опциональным? Ведь не всегда нужно его передавать в пайп. А еще я бы поменял его с 'filterOperation' местами, ведь мы можем выбрать оператор фильтрации, который не требует доп аргумент, и не бывает такого кейса, что мы передали бы второй аргумент, но не поменяли бы оператор фильтрации.

2023-01-22 20:51 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +    filterValue2: T[K] | null,
А давай это поле тоже сделаем опциональным? Ведь не всегда нужно его передавать в пайп. А еще я бы поменял его с 'filterOperation' местами, ведь мы можем выбрать оператор фильтрации, который не требует доп аргумент, и не бывает такого кейса, что мы передали бы второй аргумент, но не поменяли бы оператор фильтрации.

2023-01-22 20:51 UTC, Letto228 commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +    filterOperation: string = "eq"
Давай добавим типизацию. Можно через 'enum', можно через 'type'. Сейчас при использовании пайпа совершенно не понятно, какие операции он поддерживает, так как в типе описана абстрактная строка.

Я бы рекомендовал воспользоваться 'type' в шаблоне с ним будет комфортней работать чем с 'enum'

'''
type operation = 'eq' & '...' & ...
'''

2023-01-26 12:51 UTC, IlyaPershin commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +    filterValue2: T[K] | null,
Согласен, перенес

2023-01-26 12:51 UTC, IlyaPershin commented on src/app/shared/filter-by-param/filter-by-param.pipe.ts
> +    filterOperation: string = "eq"
Решил что лучше всё таки enum и реализовал его

2023-01-26 12:51 UTC, IlyaPershin commented
Доработки внес

2023-02-01 17:01 UTC, Letto228 approved these changes
Привет!
Да, все гуд - апрув

2023-02-01 17:01 UTC, closed without merging